name: Build Test and push
on: [push]
env:
  IMAGE_NAME: student_service
  REPO_NAME: jurrewolff
  SERVER_HOST: "172.17.0.124"
  MONGO_INITDB_ROOT_USERNAME: root
  MONGO_INITDB_ROOT_PASSWORD: verysecure
  MONGO_INITDB_DATABASE: devopscloud
  MONGO_URI: "mongodb://root:verysecure@172.17.0.124:8081/devopscloud?authSource=admin"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build docker
      run: |
        docker build . -t $REPO_NAME/$IMAGE_NAME

    - name: run docker
      run: |
        docker-compose up -d && sleep 10 && docker ps
#        docker run -d -e 27017:27017 -host=172.17.0.2 mongo:6.0.4 && sleep 10 && \
#        docker run -d -e 8080:8080 -host=172.17.0.2 $REPO_NAME/$IMAGE_NAME:latest && \
#        docker ps && sleep 5 && docker logs mongo

    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        collection: postman/collection.json
        environment: postman/environment.json
        reporters: cli
        iterationCount: 3

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}

    - name: Push image to docker hub Container Registry
      run: | 
          docker push $REPO_NAME/$IMAGE_NAME
